name: xmake build
run-name: xmake build project
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build-mode: [debug, release]
    runs-on: ${{ matrix.os }}
    steps:
      # 存储到 steps.cache_key.outputs.key
      - name: Get current date as package key
        id: cache_key
        run: echo "key=$(date +'%W')" >> $GITHUB_OUTPUT  

      - name: Check out xmake repository code
        uses: xmake-io/github-action-setup-xmake@master
        with:
          xmake-version: latest
          actions-cache-folder: .xmake-cache
          actions-cache-key: ${{ matrix.os }}-${{ steps.cache_key.outputs.key }}-action
          # build-cache: true
          # build-cache-key: ${{ matrix.os }}-${{ steps.cache_key.outputs.key }}-build
          package-cache: true
          package-cache-key: ${{ matrix.os }}-${{ steps.cache_key.outputs.key }}-packages
          project-path: ''

      - name: Check out self repository code
        uses: actions/checkout@v4

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
         version: 1.4.309.0
         cache: true

      - name: Build Project
        run: |
          # output env variable windows platform
          if [ $RUNNER_OS == 'Windows' ]; then
            echo $env:PATH
            echo $env:VULKAN_SDK
            echo $env:XMAKE_ROOT
            echo $env:XMAKE_GLOBAL
            echo $env:XMAKE_BUILD
          fi
          echo "cur path"
          pwd
          echo "ls"
          ls 
          echo ".xmake-cache"
          ls .xmake-cache
          echo ".xmake-cache/bin"
          ls .xmake-cache/bin

          xmake f -m ${{matrix.build-mode}} -y
          xmake build -y
          xmake build -y window
          xmake test
