name: xmake build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out xmake repository code
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          cache: true
      - name: Check out self repository code
        uses: actions/checkout@v4
      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
         version: 1.4.309.0
         cache: true
      - name: Run project
        run: |
          pwd
          xmake -y -vD
