name: xmake build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
