name: xmake build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out xmake repository code
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          # actions-cache-folder: '.xmake-cache'
          package-cache: true
          package-cache-key: 'ubuntu-latest-ci'
          project-path: 'nayuki_yq'
      - name: Check out self repository code
        uses: actions/checkout@v4
      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
         version: 1.4.309.0
         cache: true
      - name: Run project Debug Mode
        run: |
          xmake f -m debug -y
          xmake build -y
          xmake build -y window
          xmake test
      - name: Run project Release Mode
        run: |
          xmake f -m release -y
          xmake build -y
          xmake build -y window
          xmake test
    

